let quotes=[
    "Never speak badly of anyone - get others to do so for you.","Guard your reputation with your life.",
    "Do not directly ask for the help of others - appeal to their self - interests.",
    "Accept gifts but refuse charity.",
    "Know that good enough is not good enough.",
    "Avoid the affairs of others.",
    "Know when you have been beaten.",
    "Take advantage of every situation.",
    "Brush your teeth every chance you get.",
    "Understand the thin line between confidence and cocky.",
    "Avoid assuming responsibility.",
    "Do everything with confidence, and others will follow you.",
    "Know that praise in moderation earns favor.",
    "Do not forget that all actions have consequences.",
    "Never make decisions while intoxicated.",
    "Learn to recognise the difference between good intentions and good actions.",
    "Do not fear the person with everything but rather the person with nothing.",
    "Your past can and will be held against you - show your capacity for change.",
    "Measure success by the difference between what you had and what you have.",
    "Never curse in the presence of women or children.",
    "Know that nothing in life is deserved - everything is earned.",
    "Do not make empty promises.",
    "Learn how to read the room.",
    "Greet with a clear voice and a firm handshake.",
    "Give to the deserving not to the needy.",
    "If you dont have what you want - work harder.",
    "People can and will take advantage of you if you let them.",
    "Respect and understand different cultures and traditions.",
    "Use your emotions to push you forward not hold you back.",
    "Say please and thankyou regardless of your status.",
    "Know that pain must be felt in order to grow.",
    "If you are Tired - go to Sleep.",
    "Avoid conflict but never run away from it.",
    "Be wary of compliments and aware of the intentions behind them.",
    "Acknowledge your flaws before they can be used against you.",
    "If you show weakness you must also show perseverance.",
    "Never settle for less than what you want.",
    "Always be punctual - expect the same from others.",
    "If you cant say something nice - dont post it online.",
    "Respect few and trust even fewer.",
    "Never borrow money nor lend it.",
    "It is ok to let others go first.",
    "Always eat your friuts and vegetables unless youre alergic to them.",
    "Go take a hike.",
    "No one is better than you.",
    "Do what you want and the money will follow.",
    "Realise that time spent complaining is time wasted.",
    "Many people will have many opinions - only few of them will matter.",
    "Never exaggerate the only thing it inflates is disbelief.",
    "Strive to learn something new every day.","Improvise Adapt and Overcome.",
    "Always have a backup plan.",
    "Keep and value those who are loyal.",
    "Never doubt the abilities of others.",
    "Do not let your emotions control you.",
    "If youre not laughing once a day - youre doing it wrong.",
    "Keep your composure at all times.",
    "Winners dont use drugs.",
    "Know that a dream without action will stay a dream.",
    "Question everything.",
    "Welcome criticism and discussion.",
    "Know that it is your pains and sufferings that give your life value.",
    "Reflect on the difference between your thoughts and actions daily.",
    "Do not mistake beauty for virtue.",
    "Bring out the best in those around you.",
    "Stay Sexy and Dont Get Murdered.",
    "Remember that a problem only exists if it is acknowledged.",
    "If you receive you should most definitely give back.",
    "Know that knowledge is useless if it is not applied.",
    "Make time to spend with your family.",
    "Know that that you are responsible for your own happiness and suffering.",
    "Dont steal - the government hates competition.",
    "Trust your gut feeling.",
    "Appreciate the ability to read and write.",
    "Go say hi to the person sitting alone.",
    "Take a Shower Every Day.",
    "Know that people are sadder than they appear to be.",
    "Always Be Coding.",
    "Do or Do not - there is no try.",
    "Study words - the ability to communicate should not be overlooked.",
    "Speak of what you have done - not of what you wish to do.",
    "Be jealous but never show it.",
    "Never trust a Junkie.",
    "Take every reasonable opportunity.",
    "You cant always go later.",
    "Its ok to be Frugal.","Research before you do.",
    "Differentiate between what you want and need.",
    "dont do it tomorrow - Do it today.",
    "Master the basics.",
    "Know that any relationship will require effort on your behalf.",
    "The secret to life is to love who you are.",
    "Restrain bad thoughts before they become bad actions.",
    "Learn to smile without reason.",
    "Always speak the truth but limit how much of it is spoken.",
    "Do not appear to be hardworking - make everything seem effortless.",
    "Never exaggerate the only thing it inflates is disbelief.",
    "Be kind to everyone (initially).",
    "If life gives you lemons - tuck em",
    "Always wash your hands (wuth soap and hot water)",
    "If its not yours - dont touch it",
    "Know that life will go on without you.",
    "Can you find the Cat in the App?",
];

function displayQuote() {
    
    let index = Math.floor(Math.random() * quotes.length);

    let div = document.querySelector('#quote');
    let quote = `<div class="card">
    <img src="icons/favicon.png">
    <p>${quotes[index]}</p>
    <img src="icons/favicon.png">
   </div>
    `;
    div.innerHTML = quote;

}